"""add a email column to demo table

Revision ID: a9f2f54529fd
Revises: 744e230a91db
Create Date: 2026-06-02 13:41:06.588141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f2f54529fd'
down_revision: Union[str, Sequence[str], None] = '744e230a91db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'email')
    # ### end Alembic commands ###
